### ISSUE TITLE
if else if else if else if else if else if else if else if else if else if else if else if else if else if else if else if 

### ISSUE THREAD

**Issue by 3jq** [HausemasterIssue/SqueakerBot#2]
kys

**Comment by ghost** [comment]
else if > arrays

**Comment by HausemasterIssue** [comment]
Switch statements then.

**Comment by ghost** [comment]
> Switch statements then.

bruh I'll make a clean code version if u want

**Comment by bush-did-711** [comment]
lol

**Comment by ghost** [comment]
> Switch statements then.

(completely missed point)

**Comment by HausemasterIssue** [comment]
You want cleaner and less repetitive code correct?

**Comment by notperry12345678902** [comment]
> You want cleaner and less repetitive code correct?

what's ur disc I'll add so I can show example cause github is not too nice when it comes to pasting code in issues to show stuff

**Comment by ghost** [comment]
> You want cleaner and less repetitive code correct?

```java
    public static void main(String[] args) {
        Random random = new Random();
        String[] strings = {
            "ur",
            "mom",
            "is",
            "lesbian",
            "no",
            "cap"
        };
        System.out.println(strings[random.nextInt(6)]);
    }
```
would be way cleaner then a billion else ifs

**Comment by HausemasterIssue** [comment]
@notperry12345678902 
```
public class AskGod extends Command {
	
	private static String[] replies = {"> [SqueakerBot] It is certain.", "> [SqueakerBot] My sources say no.", "> [SqueakerBot] Absolutley.",
			"> [SqueakerBot] Never.", "> [SqueakerBot] Perhaps.", "> [SqueakerBot] Reply hazy. Ask again later.", "> [SqueakerBot] Based off your tone, no.",
			"> [SqueakerBot] In the future, yes.", "> [SqueakerBot] Better not tell you now.", "> [SqueakerBot] It is highly unlikely.",
			"> [SqueakerBot] Do not ask that question ever again.", "> [SqueakerBot] Yes.", "> [SqueakerBot] Not in a trillion years.", "> [SqueakerBot] I do not know.",
			"> [SqueakerBot] For sure.", "> [SqueakerBot] No."};
																																		
	
	public AskGod() {
		super("AskGod", new String[] {"AskGod", "Ask"});
	}
	
	@Override
	public void onRun() {
		Random random = new Random();
		int randomNum = random.nextInt((15 - 0) + 1) + 0;
		mc.player.connection.sendPacket(new CPacketChatMessage(replies[randomNum]));
		
	}

}

```
I literally just wrote that as you were typing. Plus I could make the chat message line a single method.

**Comment by ghost** [comment]
> @notperry12345678902
> 
> ```
> public class AskGod extends Command {
> 	
> 	private static String[] replies = {"> [SqueakerBot] It is certain.", "> [SqueakerBot] My sources say no.", "> [SqueakerBot] Absolutley.",
> 			"> [SqueakerBot] Never.", "> [SqueakerBot] Perhaps.", "> [SqueakerBot] Reply hazy. Ask again later.", "> [SqueakerBot] Based off your tone, no.",
> 			"> [SqueakerBot] In the future, yes.", "> [SqueakerBot] Better not tell you now.", "> [SqueakerBot] It is highly unlikely.",
> 			"> [SqueakerBot] Do not ask that question ever again.", "> [SqueakerBot] Yes.", "> [SqueakerBot] Not in a trillion years.", "> [SqueakerBot] I do not know.",
> 			"> [SqueakerBot] For sure.", "> [SqueakerBot] No."};
> 																																		
> 	
> 	public AskGod() {
> 		super("AskGod", new String[] {"AskGod", "Ask"});
> 	}
> 	
> 	@Override
> 	public void onRun() {
> 		Random random = new Random();
> 		int randomNum = random.nextInt((15 - 0) + 1) + 0;
> 		mc.player.connection.sendPacket(new CPacketChatMessage(replies[randomNum]));
> 		
> 	}
> 
> }
> ```
> 
> I literally just wrote that as you were typing. Plus I could make the chat message line a single method.

```java
random.nextInt((15 - 0) + 1) + 0
```
why do u do it like that & why do u use cpacketchat message when u can just use mc.player.sendmessage

**Comment by wawddd** [comment]
bc hes a skid lololol

**Comment by HausemasterIssue** [comment]
1. That's just the way I do random numbers, its fine.
2. When I was testing it mc.player.sendChatMessage fucked with one of my experiments, it would work the same with the mc.player.sendChatMessage now lol. I could still make it one method in a util.

**Comment by bosshacker2003** [comment]
:v

**Comment by bosshacker2003** [comment]
oi wawd

**Comment by ghost** [comment]
> bc hes a skid lololol

🚎

**Comment by wawddd** [comment]
oi monky

> oi wawd

**Comment by bosshacker2003** [comment]
:D

**Comment by wawddd** [comment]
:D

**Comment by bosshacker2003** [comment]
:VVVVVVVVVVVV

**Comment by wawddd** [comment]
ebk mouse > whoever made this garbage paste

**Comment by HausemasterIssue** [comment]
wawddd Do you play chess?

**Comment by bosshacker2003** [comment]
mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse mouse

**Comment by wawddd** [comment]
> wawddd Do you play chess?

i retired i was too good

**Comment by HausemasterIssue** [comment]
@wawddd https://lichess.org/xufHBBqy Join pussy

**Comment by wawddd** [comment]
ew lichess

**Comment by HausemasterIssue** [comment]
Cmon I'm bored join

**Comment by ghost** [comment]
> 1. That's just the way I do random numbers, its fine.
> 2. When I was testing it mc.player.sendChatMessage fucked with one of my experiments, it would work the same with the mc.player.sendChatMessage now lol. I could still make it one method in a util.

```java
random.nextInt((15 - 0) + 1) + 0;
```
minus zero?? and if ur doing plus 1 u can just do
```java
random.nextInt(16);
```
like what

**Comment by HausemasterIssue** [comment]
mc.player.connection.sendPacket(new CPacketChatMessage(replies[random.nextInt(14)]));

**Comment by bosshacker2003** [comment]
oi perry :D

**Comment by ghost** [comment]
> oi perry :D

wassup

**Comment by bosshacker2003** [comment]
hihihihihihihhihihi

**Comment by zopac** [comment]
oioioioi

**Comment by HausemasterIssue** [comment]
Cleaned up code.
