### ISSUE TITLE
still dogshit

### ISSUE THREAD

**Issue by therealbush** [HausemasterIssue/SqueakerBot#7]
https://github.com/HausemasterIssue/SqueakerBot/blob/0ed0b876150371c701ad474b7d74200cd1c80788/src/main/java/dev/hause/squeakerbot/SqueakerBot.java#L29

why are u registering a class with no listeners in it?

**Comment by therealbush** [comment]
https://github.com/HausemasterIssue/SqueakerBot/blob/0ed0b876150371c701ad474b7d74200cd1c80788/src/main/java/dev/hause/squeakerbot/command/Command.java#L28

bro doesn't know about "abstract"

**Comment by HausemasterIssue** [comment]
Thank you for your suggestions and feedback. I have improved one of your requests.
